// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMcontents(t *testing.T) {
	t.Parallel()

	query := Mcontents()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMcontentsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Mcontents().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMcontentsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Mcontents().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Mcontents().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMcontentsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := McontentSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Mcontents().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMcontentsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := McontentExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Mcontent exists: %s", err)
	}
	if !e {
		t.Errorf("Expected McontentExists to return true, but got false.")
	}
}

func testMcontentsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	mcontentFound, err := FindMcontent(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if mcontentFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMcontentsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Mcontents().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMcontentsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Mcontents().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMcontentsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	mcontentOne := &Mcontent{}
	mcontentTwo := &Mcontent{}
	if err = randomize.Struct(seed, mcontentOne, mcontentDBTypes, false, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}
	if err = randomize.Struct(seed, mcontentTwo, mcontentDBTypes, false, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mcontentOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mcontentTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Mcontents().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMcontentsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	mcontentOne := &Mcontent{}
	mcontentTwo := &Mcontent{}
	if err = randomize.Struct(seed, mcontentOne, mcontentDBTypes, false, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}
	if err = randomize.Struct(seed, mcontentTwo, mcontentDBTypes, false, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mcontentOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mcontentTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Mcontents().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func mcontentBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Mcontent) error {
	*o = Mcontent{}
	return nil
}

func mcontentAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Mcontent) error {
	*o = Mcontent{}
	return nil
}

func mcontentAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Mcontent) error {
	*o = Mcontent{}
	return nil
}

func mcontentBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Mcontent) error {
	*o = Mcontent{}
	return nil
}

func mcontentAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Mcontent) error {
	*o = Mcontent{}
	return nil
}

func mcontentBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Mcontent) error {
	*o = Mcontent{}
	return nil
}

func mcontentAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Mcontent) error {
	*o = Mcontent{}
	return nil
}

func mcontentBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Mcontent) error {
	*o = Mcontent{}
	return nil
}

func mcontentAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Mcontent) error {
	*o = Mcontent{}
	return nil
}

func testMcontentsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Mcontent{}
	o := &Mcontent{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, mcontentDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Mcontent object: %s", err)
	}

	AddMcontentHook(boil.BeforeInsertHook, mcontentBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	mcontentBeforeInsertHooks = []McontentHook{}

	AddMcontentHook(boil.AfterInsertHook, mcontentAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	mcontentAfterInsertHooks = []McontentHook{}

	AddMcontentHook(boil.AfterSelectHook, mcontentAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	mcontentAfterSelectHooks = []McontentHook{}

	AddMcontentHook(boil.BeforeUpdateHook, mcontentBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	mcontentBeforeUpdateHooks = []McontentHook{}

	AddMcontentHook(boil.AfterUpdateHook, mcontentAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	mcontentAfterUpdateHooks = []McontentHook{}

	AddMcontentHook(boil.BeforeDeleteHook, mcontentBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	mcontentBeforeDeleteHooks = []McontentHook{}

	AddMcontentHook(boil.AfterDeleteHook, mcontentAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	mcontentAfterDeleteHooks = []McontentHook{}

	AddMcontentHook(boil.BeforeUpsertHook, mcontentBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	mcontentBeforeUpsertHooks = []McontentHook{}

	AddMcontentHook(boil.AfterUpsertHook, mcontentAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	mcontentAfterUpsertHooks = []McontentHook{}
}

func testMcontentsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Mcontents().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMcontentsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(mcontentColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Mcontents().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMcontentToManyMcontentTexts(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Mcontent
	var b, c McontentText

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, mcontentTextDBTypes, false, mcontentTextColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, mcontentTextDBTypes, false, mcontentTextColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.McontentID = a.ID
	c.McontentID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.McontentTexts().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.McontentID == b.McontentID {
			bFound = true
		}
		if v.McontentID == c.McontentID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := McontentSlice{&a}
	if err = a.L.LoadMcontentTexts(ctx, tx, false, (*[]*Mcontent)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.McontentTexts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.McontentTexts = nil
	if err = a.L.LoadMcontentTexts(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.McontentTexts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testMcontentToManyAddOpMcontentTexts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Mcontent
	var b, c, d, e McontentText

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mcontentDBTypes, false, strmangle.SetComplement(mcontentPrimaryKeyColumns, mcontentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*McontentText{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, mcontentTextDBTypes, false, strmangle.SetComplement(mcontentTextPrimaryKeyColumns, mcontentTextColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*McontentText{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddMcontentTexts(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.McontentID {
			t.Error("foreign key was wrong value", a.ID, first.McontentID)
		}
		if a.ID != second.McontentID {
			t.Error("foreign key was wrong value", a.ID, second.McontentID)
		}

		if first.R.Mcontent != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Mcontent != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.McontentTexts[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.McontentTexts[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.McontentTexts().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testMcontentsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMcontentsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := McontentSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMcontentsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Mcontents().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	mcontentDBTypes = map[string]string{`ID`: `integer`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `DeletedAt`: `timestamp with time zone`, `Label`: `text`, `ContentType`: `text`, `StartAt`: `timestamp with time zone`, `EndAt`: `timestamp with time zone`, `Status`: `text`, `Xtime1`: `timestamp with time zone`, `CreatorID`: `integer`}
	_               = bytes.MinRead
)

func testMcontentsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(mcontentPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(mcontentColumns) == len(mcontentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Mcontents().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMcontentsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(mcontentColumns) == len(mcontentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Mcontent{}
	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Mcontents().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mcontentDBTypes, true, mcontentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(mcontentColumns, mcontentPrimaryKeyColumns) {
		fields = mcontentColumns
	} else {
		fields = strmangle.SetComplement(
			mcontentColumns,
			mcontentPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := McontentSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMcontentsUpsert(t *testing.T) {
	t.Parallel()

	if len(mcontentColumns) == len(mcontentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Mcontent{}
	if err = randomize.Struct(seed, &o, mcontentDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Mcontent: %s", err)
	}

	count, err := Mcontents().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, mcontentDBTypes, false, mcontentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Mcontent struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Mcontent: %s", err)
	}

	count, err = Mcontents().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
